import { chmodSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { GITHUB_ACTION_WORKFLOW, MCP_CONFIG_CURSOR, MCP_CONFIG_CLAUDE } from '../templates.js';
import { parseArgs } from '../args.js';

export const help = `de-slop init — scaffold de-slop in the current project

Usage: de-slop init [options]

Creates:
  .desloprc.json        default configuration
  .de-slop/             store dir for test-lock fingerprints
  .git/hooks/pre-commit runs 'de-slop check . --lock' on every commit

Options:
  --ci                  also write .github/workflows/de-slop.yml (GitHub Actions)
  --mcp <target>        also write MCP server config for 'cursor' or 'claude'
  --help                Show this help

Existing files are never overwritten.
`;

const CONFIG_FILE = '.desloprc.json';
const DEFAULT_CONFIG = {
  strict: true,
  maxRetries: 5,
  maxDiffLines: 500,
  exclude: ['node_modules', 'dist'],
};

const PRE_COMMIT_HOOK = `#!/bin/sh
# de-slop pre-commit hook (generated by \`de-slop init\`)
npx --no-install de-slop check . --lock
if [ $? -ne 0 ]; then
  echo "de-slop: check failed - fix the problems or bypass with 'git commit --no-verify'"
  exit 1
fi
exit 0
`;

export default async function init(argv) {
  const { options } = parseArgs(argv);
  const created = [];

  if (!existsSync(CONFIG_FILE)) {
    writeFileSync(CONFIG_FILE, `${JSON.stringify(DEFAULT_CONFIG, null, 2)}\n`, 'utf8');
    created.push(CONFIG_FILE);
  } else {
    console.log(`de-slop: ${CONFIG_FILE} already exists, leaving it untouched`);
  }

  if (!existsSync('.de-slop')) {
    mkdirSync('.de-slop', { recursive: true });
    created.push('.de-slop/');
  } else {
    console.log('de-slop: .de-slop/ already exists, leaving it untouched');
  }

  if (existsSync('.git')) {
    const hookPath = join('.git', 'hooks', 'pre-commit');
    if (!existsSync(hookPath)) {
      writeFileSync(hookPath, PRE_COMMIT_HOOK, { mode: 0o755 });
      chmodSync(hookPath, 0o755);
      created.push('.git/hooks/pre-commit');
    } else {
      console.log('de-slop: .git/hooks/pre-commit already exists, leaving it untouched');
    }
  }

  if (options.ci) {
    const workflowDir = join('.github', 'workflows');
    const workflowPath = join(workflowDir, 'de-slop.yml');
    if (!existsSync(workflowPath)) {
      mkdirSync(workflowDir, { recursive: true });
      writeFileSync(workflowPath, GITHUB_ACTION_WORKFLOW, 'utf8');
      created.push('.github/workflows/de-slop.yml');
    } else {
      console.log('de-slop: .github/workflows/de-slop.yml already exists, leaving it untouched');
    }
  }

  if (options.mcp) {
    const target = String(options.mcp).toLowerCase();
    const template = target === 'cursor' ? MCP_CONFIG_CURSOR : target === 'claude' ? MCP_CONFIG_CLAUDE : null;
    if (template === null) {
      console.error(`de-slop: --mcp must be 'cursor' or 'claude', got '${target}'`);
      return 1;
    }
    const mcpPath = target === 'cursor' ? '.mcp.json' : '.claude.json';
    if (!existsSync(mcpPath)) {
      writeFileSync(mcpPath, template, 'utf8');
      created.push(mcpPath);
    } else {
      console.log(`de-slop: ${mcpPath} already exists, leaving it untouched`);
    }
  }

  if (created.length > 0) {
    console.log(`de-slop: created ${created.join(', ')}`);
  } else {
    console.log('de-slop: nothing to do — everything is already in place');
  }
  return 0;
}
